apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bti-ui-cicd
  name: bti-ui-cicd
  namespace: bti-cim
  selfLink: /api/v1/namespaces/bti-cim/services/bti-ui-cicd
spec:
  ports:
  - name: port-2
    nodePort: "30422"
    port: "9443"
    protocol: TCP
    targetPort: "9443"
  selector:
    io.kompose.service: bti-ui-cicd
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
  
